version: "3"

services:
    app:
        build: .
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: mysql-container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dinacom24
            MYSQL_USER: dinacom24
            MYSQL_PASSWORD: dinacom24
            MYSQL_ROOT_PASSWORD: dinacom24
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx-container
        restart: always
        ports:
            - "9090:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
