version: "3"

services:
    app:
        build: .
        restart: unless-stopped
        container_name: dinacom24-app-container
        volumes:
            - .:/var/www
            - ./storage/app/public:/var/www/public/storage
        networks:
            - app-network
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: dinacom24-mysql-container
        restart: always
        environment:
            MYSQL_DATABASE: dinacom24
            MYSQL_USER: dinacom24
            MYSQL_PASSWORD: dinacom24
            MYSQL_ROOT_PASSWORD: dinacom24
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: dinacom24-nginx-container
        restart: always
        ports:
            - "9090:80"
        volumes:
            - .:/var/www
            - ./storage/app/public:/var/www/public/storage
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
volumes:
    mysql_data:
